server:
  port: 8081
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cooperative
    username: postgres
    password: postgres
  security:
    user:
      name: m97
      password: P@ssw0rd

map-collection:
  message:
    S001: "200|Success!"
    S002: "200|Data not found."
    S003: "200|Data successfully added."
    S004: "200|Data successfully updated."
    E001: "500|Error occured on service."
    E002: "500|Error occured on resource."
    E003: "404|Id not found."
    E004: "401|Unauthorized."
    E005: "400|{args1} - {args2} already exist."
    E006: "400|{args1} is required."
    E007: "400|{args1} cannot be less than {args2} characters."
    E008: "400|{args1} cannot be greater than {args2} characters."
    E009: "400|{args1} must be {args2} characters long."
    E010: "400|{args1} can only be filled with numbers."
    E011: "400|{args1} can only be filled with {args2}."
    E012: "400|{args1} value must have format {args2}."
    E013: "400|{args1} value must in range of {args2} - {args3}."
    E014: "400|{args1} cannot be later than {args2}."
    E015: "400|Balance not enaugh."

logging:
  level:
    '[com.m97]': DEBUG